she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(),name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory')
    ]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include ,path


urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls'))

]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView
from .views import UserProfile

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('profile/<int:pk>/', UserProfile.as_view(), name='profile'),

]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()

she_codes_news/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User


# Create your models here.
class CustomUser(AbstractUser):
    pass
    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content']
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'),
            attrs={'class':'form-control',
            'placeholder':'Select a date',
            'type':'date'}),
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.views import generic
from .models import NewsStory
from django.urls import reverse_lazy
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['latest_stories'] = NewsStory.objects.all()[:4]
    #     context['all_stories'] = NewsStory.objects.all()
        
    #     return context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        createstory = NewsStory.objects.all().order_by('-pub_date')
        context['latest_stories'] = createstory[:4]
        context['all_stories'] = createstory
        return context

        # have a look here this is the view for the profile page
class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name: 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')
   



    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

she_codes_news/users/views.py
# Create your views here.
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic 
from .models import CustomUser 
from .forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required



class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'



class UserProfile(generic.ListView):
    template_name = 'users/profile.html'
    model = CustomUser
    context_object_name = 'profile'

    

she_codes_news/templates/base.html
{%load static %}


<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>
        {% block content %}{% endblock %}
        <!-- content blocks here -->
    </body>
</html>

she_codes_news/templates/nav.html
<nav>    

    <div class="container-lamp">
        <div class="lamp">
            <div class="stand"></div>
            <div class="bulb"></div>
            <input type="checkbox">
        </div>
    </div>


    <a href="{% url 'news:index' %}">Home</a>
    <a href="{% url 'users:createAccount' %}">Create Account</a>

    {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}

    {% if request.user.is_authenticated %}
        <a href="{% url 'users:profile' request.user.id %}">{{ user.username }}</a>
    {% endif %}

    
</nav>