she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(),name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory')
    ]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content']
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'),
            attrs={'class':'form-control',
            'placeholder':'Select a date',
            'type':'date'}),
        }

she_codes_news/news/views.py
from django.views import generic
from .models import NewsStory
from django.urls import reverse_lazy
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['latest_stories'] = NewsStory.objects.all()[:4]
    #     context['all_stories'] = NewsStory.objects.all()
        
    #     return context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        createstory = NewsStory.objects.all().order_by('-pub_date')
        context['latest_stories'] = createstory[:4]
        context['all_stories'] = createstory
        return context

        # have a look here this is the view for the profile page
class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name: 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')
   



    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

she_codes_news/news/templates/news/createStory.html
{% extends "base.html"%}
{% block content %}
<form action=""method="post">
        <!-- #security for form -->
    {% csrf_token %} 
    <!-- Double brackets are veriables -->
    {{ form.as_p }} 
    <input type= "submit" value ="submit">
    
</form>

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}    



{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
{% endblock %}

{% block content %}
<div class="container">
<button type="button" class="btn">
<a href="{% url 'news:newStory' %}">Write New Story</a>
</button>
</div>


<h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story postion=forloop.counter %}
            {% endfor %}
        {% else %}
            {% include "./storyCard.html" with story=story %}
        {% endif %}
    </div>
    {% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}


    <div id="story-wrapper">
    <div id="story-wrapper">
        <h2>{{ story.title }}</h2>
        <h4>{{ story.author }}</h4>
        <div id="story-content">
            <img src="http://placekitten.com/200/300/500">
            {{ story.content|linebreaks }}
        </div>
    </div>
    </div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href=" { % url 'news:story' story.id %} ">
        {% if position < 5 %}
            <img src="http://placekitten.com/200/300">
        {% else %}
            <img src="http://placekitten.com/300">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>